---
- name: Ensure Nginx configuration directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    mode: "0755"

- name: Template for creating Nginx proxy configuration
  ansible.builtin.template:
    src: nginx_proxy_conf.j2
    dest: /etc/nginx/sites-available/{{ item.server_name }}
    mode: "0644"
  vars:
    nginx_proxy_ssl_enabled: "{{ item.ssl_enabled }}"
    nginx_proxy_backend_port: "{{ item.upstream.split(':')[-1] }}"
    nginx_proxy_ssl_certificate: "/etc/nginx/ssl/{{ item.server_name }}/fullchain.pem"
    nginx_proxy_ssl_certificate_key: "/etc/nginx/ssl/{{ item.server_name }}/privkey.pem"
  notify:
    - Restart Nginx
  with_items: "{{ nginx_proxy_configs }}"
