---
# handlers file for nginx_ssl
- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
  become: true

- name: Stop Nginx
  ansible.builtin.service:
    name: nginx
    state: stopped
  become: true

- name: Configure Nginx for SSL
  ansible.builtin.include_tasks: tasks/configure_nginx_for_ssl.yml
