---
- name: Check if Docker is installed
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_installed

- name: Include docker role if Docker is not installed
  ansible.builtin.include_role:
    name: docker
  when: not docker_installed.stat.exists

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Pull Portainer Agent image
  community.docker.docker_image:
    name: "{{ portainer_agent_image }}"
    source: pull

- name: Run Portainer Agent container
  community.docker.docker_container:
    name: "{{ portainer_agent_container_name }}"
    image: "{{ portainer_agent_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ portainer_agent_host_port }}:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    cleanup: true
