# Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"  # Choose your desired box/version
  # https://app.vagrantup.com/boxes/search

  config.vm.network "private_network", type: "dhcp"  # Configure networking

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"  # Customize VM memory size if needed
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"  # Specify your playbook file
    ansible.inventory_path = "inventory"  # Specify your inventory file if separate
    # Optionally, you can add other Ansible-related configurations here
  end
end

