---
# additional tasks for installing certbot
- name: Install EPEL repository # noqa fqcn
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_distribution in ["CentOS", "Rocky", "AlmaLinux"]

- name: Install Certbot
  ansible.builtin.package:
    name: certbot
    state: present
    update_cache: true
