---
# tasks file for nginx_ssl
- name: Include tasks to install Certbot
  ansible.builtin.include_tasks: install_certbot.yml

- name: Include tasks to obtain SSL certificates
  ansible.builtin.include_tasks: obtain_certificates.yml

- name: Include tasks to configure Nginx for SSL
  ansible.builtin.include_tasks: configure_nginx.yml
