- name: Ensure certificate and key files are present
  ansible.builtin.stat:
    path: "{{ item }}"
  register: cert_files
  with_items:
    - /etc/nginx/ssl/{{ portainer_proxy }}/fullchain.pem
    - /etc/nginx/ssl/{{ portainer_proxy }}/privkey.pem
  failed_when: cert_files.stat.exists == false

- name: Stop the Portainer stack
  ansible.builtin.command: docker stack rm portainer
  ignore_errors: true
  register: stop_stack
  changed_when: stop_stack.rc == 0

# - name: List Docker secrets
#   ansible.builtin.command: docker secret ls
#   register: docker_secrets_list
#   changed_when: false

# - name: Debug Docker secrets
#   ansible.builtin.debug:
#     var: docker_secrets_list.stdout

- name: Create Docker secret for SSL certificate
  ansible.builtin.command: docker secret create portainer.sslcert /etc/nginx/ssl/{{ portainer_proxy }}/fullchain.pem
  ignore_errors: true
  register: sslcert_secret
  changed_when: sslcert_secret.rc == 0

- name: Create Docker secret for SSL key
  ansible.builtin.command: docker secret create portainer.sslkey /etc/nginx/ssl/{{ portainer_proxy }}/privkey.pem
  ignore_errors: true
  register: sslkey_secret
  changed_when: sslkey_secret.rc == 0

- name: Verify Docker SSL secrets creation
  ansible.builtin.command: docker secret ls
  register: docker_secrets
  changed_when: false

- name: Ensure Docker SSL secrets exist
  ansible.builtin.assert:
    that:
      - "'portainer.sslcert' in docker_secrets.stdout"
      - "'portainer.sslkey' in docker_secrets.stdout"
