# Description: This playbook installs Docker on the target system.
# Usage: ansible-playbook -i inventory.ini --vault-password-file ansible_ssh_key.pub --diff docker_setup.yml --limiit=<host>
# Author: Dimitrios Chralampidis (dimitrios@charalampidis.pro)
# Tested on:
#   - Debian 12
#   - Ubuntu 24.04 LTS
#   - Fedora 40
#   - CentOS Stream 9
#   - Rocky Linux 9
#   - AlmaLinux 9
---
- name: Set up Docker
  hosts: all
  become: true
  roles:
    - docker
