---
# ansible-playbook -i inventory.ini --vault-password-file ansible_ssh_key.pub --diff draft.yml --limiit=<host>
- name: Update Remote System
  import_playbook: "system_update.yml"

- name: Reboot Remote System
  import_playbook: "system_reboot.yml"

- name: Configure a Firewall and Install Docker
  hosts: all
  become: true
  roles:
    - role: firewall
      vars:
        firewall_allowed_ports:
          - 22 # Don't lock yourself out
          - 80
          - 443
    - role: docker
