---
# ansible-playbook -i inventory.ini --vault-password-file ansible_ssh_key.pub --diff draft.yml --limiit=<host>
- name: Update remote system(s)
  import_playbook: "system_update.yml"

- name: Reboot remote system
  import_playbook: "system_reboot.yml"

- name: Install Docker
  hosts: all
  become: true
  roles:
    - docker

- name: Install Nginx and configure firewall for Nginx
  hosts: all
  become: true
  roles:
    - role: firewall
      vars:
        firewall_allowed_ports:
          - 22 # Don't lock yourself out
          - 80
    - role: nginx
