---
# ansible-playbook -i inventory.ini --vault-password-file ansible_ssh_key.pub --diff firewall_setup.yml --limiit=<host>
- name: Configure a Firewall
  hosts: all
  become: true
  roles:
    - role: firewall
      vars:
        firewall_allowed_ports:
          - 22 # Don't lock yourself out
          - 80
          - 443
