---
# Usage: ansible-playbook -i inventory.ini --vault-password-file ansible_ssh_key.pub --diff nginx_setup.yml --limiit=<host>
- name: Install Nginx and configure firewall for Nginx
  hosts: all
  become: true
  roles:
    - role: firewall
      vars:
        firewall_allowed_ports:
          - 22 # Don't lock yourself out
          - 80 # HTTP
    - role: nginx
