---
# Usage: ansible-playbook -i inventory.ini --vault-password-file ansible_ssh_key.pub --diff nginx_setup.yml --limiit=<host>
- name: Install Nginx and configure firewall for Nginx
  hosts: all
  become: true

  vars:
    firewall_allowed_ports:
      - 22 # SSH - Don't lock yourself out
      - 80 # HTTP
      - 443 # HTTPS
    nginx_proxy_configs:
      - server_name: snail-trading.com
        upstream: 127.0.0.1:8080
        ssl: enabled
        ssl_email: webmaster@snail-trading.com
      - server_name: app1.snail-trading.com
        upstream: 127.0.0.1:8081
        ssl: enabled
        ssl_email: webmaster1@snail-trading.com
      - server_name: app2.snail-trading.com
        upstream: 127.0.0.1:8082
        ssl: disabled

  tasks:
    - name: Include firewall role
      ansible.builtin.include_role:
        name: firewall
    - name: Include nginx role
      ansible.builtin.include_role:
        name: nginx
    - name: Include docker role
      ansible.builtin.include_role:
        name: docker
    - name: Include portainer agent role
      ansible.builtin.include_role:
        name: portainer_agent
