# Description: This playbook installs the Portainer Agent on the target system.
# Usage: ansible-playbook -i inventory.ini --vault-password-file ansible_ssh_key.pub --diff portainer_agent_setup.yml --limiit=<host>
# Author: Dimitrios Chralampidis (dimitrios@charalampidis.pro)
# Tested on:
#   - Debian 12
#   - Ubuntu 24.04 LTS
#   - Fedora 40
#   - CentOS Stream 9
#   - Rocky Linux 9
#   - AlmaLinux 9
---
- name: Portainer Agent Setup
  hosts: all
  become: true
  roles:
    - portainer_agent
