---
- name: Reboot
  hosts: all
  become: true
  tasks:
    - name: Reboot the system
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 600
        test_command: uptime
        connect_timeout: 5
