# Description: This playbook reboots the system.
# Usage: ansible-playbook -i inventory.ini --vault-password-file ansible_ssh_key.pub --diff system_reboot.yml --limiit=<host>
# Author: Dimitrios Chralampidis (dimitrios@charalampidis.pro)
# Tested on:
#   - Debian 12
#   - Ubuntu 24.04 LTS
#   - Fedora 40
#   - CentOS Stream 9
#   - Rocky Linux 9
#   - AlmaLinux 9
---
- name: System Reboot
  hosts: all
  become: true
  tasks:
    - name: Reboot the system
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 600
        test_command: uptime
        connect_timeout: 5
