---
# Tasks for rebooting the system by importing this file into another playbook
- name: Check system uptime before reboot
  ansible.builtin.command: uptime
  register: pre_reboot_uptime
  changed_when: false

- name: Display system uptime before reboot
  ansible.builtin.debug:
    msg: "System uptime before reboot: {{ pre_reboot_uptime.stdout }}"

- name: Reboot the system
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    reboot_timeout: 600
    test_command: uptime
    connect_timeout: 30
    pre_reboot_delay: 10
  environment:
    ANSIBLE_SSH_RETRIES: "5" # Number of retries

- name: Check system uptime after reboot
  ansible.builtin.command: uptime
  register: post_reboot_uptime
  changed_when: false

- name: Display system uptime after reboot
  ansible.builtin.debug:
    msg: "System uptime after reboot: {{ post_reboot_uptime.stdout }}"
